version: '3.1'
services:
  stats-server:
    build: stat/stat-server
    image: statistic-server
    container_name: statistic-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING.DATASOURCE.USERNAME=stats
      - SPRING.DATASOURCE.PASSWORD=stats

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  #ewm-service:
   # ports:
   #   - "8080:8080"

  #ewm-db:
  #  image: postgres:14-alpine
