version: '3.1'
services:
  stats-server:
    build: ./stat/stat-server
    image: statistic-server
    container_name: statistic-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_HOST=stats-db
        DB_PORT=5432

  stats-db:
    image: postgres:14.6
    container_name: statsDb
    restart: always
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ./main
    container_name: main-server
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewmDB:5432/ewmDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EWM-STATS-SERVICE_URI=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewmDB
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=ewmDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
